// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Puluj.Analytics.Persistence;

#nullable disable

namespace Puluj.Analytics.Persistence.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260918022007_ForgetMessageLifecycle")]
    partial class ForgetMessageLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Puluj.Analytics.Persistence.AnalysisRun", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RunId"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("instance");

                    b.Property<int>("MessagesFingerprinted")
                        .HasColumnType("integer")
                        .HasColumnName("messages_fingerprinted");

                    b.Property<int>("MessagesScanned")
                        .HasColumnType("integer")
                        .HasColumnName("messages_scanned");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WatermarkFrom")
                        .HasColumnType("bigint")
                        .HasColumnName("watermark_from");

                    b.Property<long>("WatermarkTo")
                        .HasColumnType("bigint")
                        .HasColumnName("watermark_to");

                    b.HasKey("RunId")
                        .HasName("pk_runs");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_runs_started_at");

                    b.ToTable("runs", "analytics");
                });

            modelBuilder.Entity("Puluj.Analytics.Persistence.AnalyticsState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_state");

                    b.ToTable("state", "analytics");
                });

            modelBuilder.Entity("Puluj.Analytics.Persistence.MessageFingerprint", b =>
                {
                    b.Property<long>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<bool>("IsEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edit");

                    b.Property<string>("PostKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("post_key");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.HasKey("RawMessageId")
                        .HasName("pk_messages");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_messages_published_at");

                    b.HasIndex("SourceId", "PublishedAt")
                        .HasDatabaseName("ix_messages_source_id_published_at");

                    b.ToTable("messages", "analytics");
                });

            modelBuilder.Entity("Puluj.Analytics.Persistence.TrackFirst", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int>("TargetCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("target_category_id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_code");

                    b.Property<int>("Firsts")
                        .HasColumnType("integer")
                        .HasColumnName("firsts");

                    b.Property<int>("LagCount")
                        .HasColumnType("integer")
                        .HasColumnName("lag_count");

                    b.Property<double>("LagSecondsSum")
                        .HasColumnType("double precision")
                        .HasColumnName("lag_seconds_sum");

                    b.Property<int>("Participations")
                        .HasColumnType("integer")
                        .HasColumnName("participations");

                    b.HasKey("Day", "SourceId", "TargetCategoryId")
                        .HasName("pk_track_firsts");

                    b.ToTable("track_firsts", "analytics");
                });
#pragma warning restore 612, 618
        }
    }
}
