// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Puluj.Analytics.Persistence;

#nullable disable

namespace Puluj.Analytics.Persistence.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260917143944_RemoveCopyDetection")]
    partial class RemoveCopyDetection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Puluj.Analytics.Persistence.AnalysisRun", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RunId"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("instance");

                    b.Property<int>("MessagesFingerprinted")
                        .HasColumnType("integer")
                        .HasColumnName("messages_fingerprinted");

                    b.Property<int>("MessagesScanned")
                        .HasColumnType("integer")
                        .HasColumnName("messages_scanned");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WatermarkFrom")
                        .HasColumnType("bigint")
                        .HasColumnName("watermark_from");

                    b.Property<long>("WatermarkTo")
                        .HasColumnType("bigint")
                        .HasColumnName("watermark_to");

                    b.HasKey("RunId")
                        .HasName("pk_runs");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_runs_started_at");

                    b.ToTable("runs", "analytics");
                });

            modelBuilder.Entity("Puluj.Analytics.Persistence.AnalyticsState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_state");

                    b.ToTable("state", "analytics");
                });

            modelBuilder.Entity("Puluj.Analytics.Persistence.MessageFingerprint", b =>
                {
                    b.Property<long>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<bool>("IsEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edit");

                    b.Property<string>("PostKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("post_key");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.HasKey("RawMessageId")
                        .HasName("pk_messages");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_messages_published_at");

                    b.HasIndex("SourceId", "PublishedAt")
                        .HasDatabaseName("ix_messages_source_id_published_at");

                    b.ToTable("messages", "analytics");
                });

            modelBuilder.Entity("Puluj.Analytics.Persistence.TrackFirst", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int>("TargetCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("target_category_id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_code");

                    b.Property<int>("Firsts")
                        .HasColumnType("integer")
                        .HasColumnName("firsts");

                    b.Property<int>("LagCount")
                        .HasColumnType("integer")
                        .HasColumnName("lag_count");

                    b.Property<double>("LagSecondsSum")
                        .HasColumnType("double precision")
                        .HasColumnName("lag_seconds_sum");

                    b.Property<int>("Participations")
                        .HasColumnType("integer")
                        .HasColumnName("participations");

                    b.HasKey("Day", "SourceId", "TargetCategoryId")
                        .HasName("pk_track_firsts");

                    b.ToTable("track_firsts", "analytics");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Analytics.MessageLifecycle", b =>
                {
                    b.Property<long>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.PrimitiveCollection<long[]>("AlertIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("alert_ids");

                    b.Property<string>("AnalysisOutcome")
                        .HasColumnType("text")
                        .HasColumnName("analysis_outcome");

                    b.Property<DateTimeOffset?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.PrimitiveCollection<string[]>("BranchesDone")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("branches_done");

                    b.Property<bool>("CompletionAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("completion_available");

                    b.Property<DateTimeOffset?>("DomainCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("domain_completed_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.PrimitiveCollection<string[]>("ExpectedBranches")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("expected_branches");

                    b.Property<int>("FactCount")
                        .HasColumnType("integer")
                        .HasColumnName("fact_count");

                    b.Property<Guid?>("GenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_id");

                    b.Property<bool>("HasPayload")
                        .HasColumnType("boolean")
                        .HasColumnName("has_payload");

                    b.Property<bool>("HasText")
                        .HasColumnType("boolean")
                        .HasColumnName("has_text");

                    b.PrimitiveCollection<long[]>("IncidentIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("incident_ids");

                    b.Property<bool>("IsEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edit");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lane");

                    b.Property<long>("LlmCacheTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("llm_cache_tokens");

                    b.Property<int>("LlmCalls")
                        .HasColumnType("integer")
                        .HasColumnName("llm_calls");

                    b.Property<decimal>("LlmCostUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("llm_cost_usd");

                    b.Property<long>("LlmInputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("llm_input_tokens");

                    b.Property<int>("LlmLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("llm_latency_ms");

                    b.Property<long>("LlmOutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("llm_output_tokens");

                    b.Property<string>("Method")
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceMessageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_message_key");

                    b.Property<string>("SourceOfTruth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_of_truth");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_revision");

                    b.Property<DateTimeOffset?>("StoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stored_at");

                    b.Property<int>("TextLength")
                        .HasColumnType("integer")
                        .HasColumnName("text_length");

                    b.Property<string>("Timings")
                        .HasColumnType("text")
                        .HasColumnName("timings");

                    b.Property<bool>("TimingsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("timings_available");

                    b.PrimitiveCollection<long[]>("TrackIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("track_ids");

                    b.Property<int>("UnlocatedFacts")
                        .HasColumnType("integer")
                        .HasColumnName("unlocated_facts");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Versions")
                        .HasColumnType("text")
                        .HasColumnName("versions");

                    b.HasKey("RawMessageId", "RunId")
                        .HasName("pk_message_lifecycle");

                    b.ToTable("message_lifecycle", "analytics", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
