import json, io, os
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
top = json.load(io.open(os.path.join(ROOT, "topology.json"), encoding="utf-8"))
out = []
A = out.append
A("# AsyncAPI 3.0 registry шини Puluj (P01, ADR-0002). Генерується з topology.json (scripts у contracts/messaging/README.md);")
A("# рукописні правки — лише через topology.json + повторну генерацію. Broker arguments (quorum, DLX, delivery-limit) — topology.json.queue_policies (P02).")
A("asyncapi: 3.0.0")
A("info:")
A("  title: Puluj message platform")
A(f"  version: '{top['topology_version']}.0.0'")
A("  description: |")
A("    Транспортні події та команди між collectors, воркерами й read-side (plan §3–6).")
A("    Envelope — schemas/envelope.schema.json; payload кожного типу — schemas/events/*.schema.json.")
A(f"    Status: {top['status']} (ADR-0001/0002 accepted у P02); з P03 archive active (v2), з P04 raw-writer active (v3), решта — planned.")
A("defaultContentType: application/json")
A("servers:")
A("  local:")
A("    host: localhost:5672")
A("    protocol: amqp")
A("    description: Один RabbitMQ контейнер для розробки (ADR-0001, dev profile закріплено P02: rabbitmq:4.3-management, Compose profile broker; HA — P16).")
A("channels:")
for et, ev in top["events"].items():
    cid = et.replace(".", "_")
    A(f"  {cid}:")
    A(f"    address: puluj.{{lane}}.{et}")
    A(f"    title: {et}")
    A(f"    description: kind={ev['kind']}; producer={ev['producer']}; replay_source={str(ev['replay_source']).lower()}")
    A("    parameters:")
    A("      lane:")
    A("        enum: [live, history, replay]")
    A("    messages:")
    A(f"      {cid}:")
    A(f"        $ref: '#/components/messages/{cid}'")
    A("    bindings:")
    A("      amqp:")
    A("        is: routingKey")
    A("        exchange:")
    A(f"          name: {top['exchange']['name']}")
    A(f"          type: {top['exchange']['type']}")
    A(f"          durable: {str(top['exchange']['durable']).lower()}")
    A("          autoDelete: false")
A("operations:")
for et, ev in top["events"].items():
    cid = et.replace(".", "_")
    A(f"  send_{cid}:")
    A("    action: send")
    A(f"    channel:")
    A(f"      $ref: '#/channels/{cid}'")
    A(f"    summary: producer {ev['producer']}")
    A("    messages:")
    A(f"      - $ref: '#/channels/{cid}/messages/{cid}'")
for sid, sub in top["subscriptions"].items():
    for et in sub["bindings"]:
        cid = et.replace(".", "_")
        A(f"  receive_{sid.replace('-', '_')}_{cid}:")
        A("    action: receive")
        A(f"    channel:")
        A(f"      $ref: '#/channels/{cid}'")
        A(f"    summary: subscription {sid} (required={str(sub['required']).lower()}, owner_task={sub['owner_task']}, status={sub['status']})")
        A("    messages:")
        A(f"      - $ref: '#/channels/{cid}/messages/{cid}'")
        A("    bindings:")
        A("      amqp:")
        A("        ack: true")
        A("    x-queue-name-pattern: " + top["queue_name_pattern"].replace("{subscription_id}", sid))
        A("    x-queue-policy: " + sub["queue_policy"])
        A("    x-lanes: [" + ", ".join(sub["lanes"]) + "]")
A("components:")
A("  messages:")
for et, ev in top["events"].items():
    cid = et.replace(".", "_")
    A(f"    {cid}:")
    A(f"      name: {et}")
    A(f"      title: {et}")
    A(f"      contentType: application/json")
    A(f"      x-event-type: {et}")
    A(f"      x-kind: {ev['kind']}")
    A(f"      x-schema-version: '{ev['schema_version']}'")
    A(f"      x-producer: {ev['producer']}")
    A(f"      x-required-subscriptions: [{', '.join(ev['required_subscriptions'])}]")
    if "owner" in ev:
        A(f"      x-owner: {ev['owner']}")
    A("      payload:")
    A("        allOf:")
    A("          - $ref: 'schemas/envelope.schema.json'")
    A("          - type: object")
    A("            properties:")
    A("              event_type:")
    A(f"                const: {et}")
    A("              payload:")
    A(f"                $ref: '{ev['schema']}'")
io.open(os.path.join(ROOT, "asyncapi.yaml"), "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("asyncapi.yaml", len(out), "lines")
