<#
.SYNOPSIS
Runs the U13 public-UI release gate in a clean, disposable test profile.

.DESCRIPTION
The gate deliberately removes PULUJ_TEST_CONNECTION so PipelineFixture always starts
Testcontainers PostGIS.  It never points a test at a developer, staging, or production
database.  Browser scenarios remain useful UI-contract coverage, but they are recorded
separately from the provider-backed API/integration checks: mocked routes must not be
reported as a full backend acceptance result.

The output folder contains TRX files, the Playwright HTML report and a small manifest
with the checked commit and runner details.  Do not commit secrets, raw message content,
or connection strings from a local run.
#>
param(
    [string]$OutputDirectory = '../artifacts/u13-release',
    [switch]$SkipBrowser
)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$output = [IO.Path]::GetFullPath((Join-Path $root $OutputDirectory))
$savedConnection = $env:PULUJ_TEST_CONNECTION
$savedReset = $env:PULUJ_TEST_ALLOW_RESET
$savedEvidenceDirectory = $env:PULUJ_TEST_EVIDENCE_DIR
$savedPlaywrightReportDirectory = $env:PLAYWRIGHT_HTML_OUTPUT_DIR
$gateOutcomes = [System.Collections.Generic.List[object]]::new()
$runSucceeded = $false

function Invoke-Gate([string[]]$Command) {
    $startedAtUtc = [DateTime]::UtcNow.ToString('O')
    & $Command[0] $Command[1..($Command.Length - 1)]
    $exitCode = $LASTEXITCODE
    $gateOutcomes.Add([ordered]@{
        command = $Command -join ' '
        startedAtUtc = $startedAtUtc
        finishedAtUtc = [DateTime]::UtcNow.ToString('O')
        exitCode = $exitCode
    })
    if ($exitCode -ne 0) {
        throw "U13 gate command failed ($exitCode): $($Command -join ' ')"
    }
}

function Get-ToolVersion([string]$Tool, [string[]]$Arguments) {
    if ($null -eq (Get-Command $Tool -ErrorAction SilentlyContinue)) {
        return $null
    }
    try {
        return (& $Tool @Arguments 2>$null | Select-Object -First 1).ToString().Trim()
    } catch {
        return $null
    }
}

function Get-TrxSummary([IO.FileInfo]$File) {
    try {
        [xml]$document = Get-Content -Raw $File.FullName
        $counters = $document.SelectSingleNode("//*[local-name()='Counters']")
        if ($null -eq $counters) {
            return [ordered]@{ file = $File.Name; parsed = $false }
        }
        return [ordered]@{
            file = $File.Name
            parsed = $true
            total = [int]$counters.GetAttribute('total')
            passed = [int]$counters.GetAttribute('passed')
            failed = [int]$counters.GetAttribute('failed')
            skipped = [int]$counters.GetAttribute('inconclusive') + [int]$counters.GetAttribute('notExecuted')
        }
    } catch {
        return [ordered]@{ file = $File.Name; parsed = $false; error = $_.Exception.Message }
    }
}

try {
    New-Item -ItemType Directory -Force -Path $output | Out-Null

    # PipelineFixture rejects external databases by default.  Clearing both variables
    # makes the runner independent from a caller's local configuration and forces a
    # disposable Testcontainers database.
    Remove-Item Env:PULUJ_TEST_CONNECTION -ErrorAction SilentlyContinue
    Remove-Item Env:PULUJ_TEST_ALLOW_RESET -ErrorAction SilentlyContinue
    $env:PULUJ_TEST_EVIDENCE_DIR = $output
    $env:PLAYWRIGHT_HTML_OUTPUT_DIR = Join-Path $output 'playwright-report'

    Push-Location $root
    try {
        Invoke-Gate @('dotnet', 'test', 'tests/Puluj.Api.Tests/Puluj.Api.Tests.csproj', '--logger', "trx;LogFileName=u13-api.trx", '--results-directory', $output)
        Invoke-Gate @('dotnet', 'test', 'tests/Puluj.Integration.Tests/Puluj.Integration.Tests.csproj', '--logger', "trx;LogFileName=u13-postgis.trx", '--results-directory', $output)
        Invoke-Gate @('dotnet', 'build', 'Puluj.sln', '--no-restore')
        Invoke-Gate @('dotnet', 'test', 'Puluj.sln', '--no-build', '--no-restore', '--logger', 'trx;LogFilePrefix=u13-solution-', '--results-directory', $output)

        if (-not $SkipBrowser) {
            Push-Location (Join-Path $root 'web')
            try {
                Invoke-Gate @('npm', 'ci')
                Invoke-Gate @('npm', 'run', 'lint')
                Invoke-Gate @('npm', 'test')
                # U13 releases the public client.  The admin bundle has its own release
                # path and is intentionally not regenerated by this public gate.
                Invoke-Gate @('npm', 'run', 'build:user')
                Invoke-Gate @('npx', 'playwright', 'test', '--output', (Join-Path $output 'playwright'))
            } finally {
                Pop-Location
            }
        }
        $runSucceeded = $true
    } finally {
        Pop-Location
    }
} finally {
    if (Test-Path $output) {
        $publicIndex = Join-Path $root 'src/Puluj.Api/wwwroot/index.html'
        $trxFiles = @(Get-ChildItem -Path $output -Filter '*.trx' -File -ErrorAction SilentlyContinue)
        $manifest = [ordered]@{
            task = 'U13'
            commit = (git -C $root rev-parse HEAD).Trim()
            completedAtUtc = [DateTime]::UtcNow.ToString('O')
            succeeded = $runSucceeded
            disposableDatabase = $true
            browser = if ($SkipBrowser) { 'skipped-by-operator' } else { 'playwright-ui-contract-suite' }
            publicIndexSha256 = if (Test-Path $publicIndex) { (Get-FileHash $publicIndex -Algorithm SHA256).Hash } else { $null }
            environment = [ordered]@{
                operatingSystem = [System.Environment]::OSVersion.VersionString
                architecture = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()
                processorCount = [System.Environment]::ProcessorCount
                dockerVersion = Get-ToolVersion 'docker' @('version', '--format', '{{.Server.Version}}')
                dotnetVersion = Get-ToolVersion 'dotnet' @('--version')
                nodeVersion = Get-ToolVersion 'node' @('--version')
            }
            commands = @($gateOutcomes)
            testResults = @($trxFiles | ForEach-Object { Get-TrxSummary $_ })
            note = 'The browser suite uses deterministic mocked API routes. Provider-backed API and PostGIS results are adjacent. A production-like browser journey and its measured performance gate remain required release evidence.'
        }
        $manifest | ConvertTo-Json -Depth 4 | Set-Content -Encoding utf8 (Join-Path $output 'manifest.json')
    }
    foreach ($setting in @(
        @{ Name = 'PULUJ_TEST_CONNECTION'; Value = $savedConnection },
        @{ Name = 'PULUJ_TEST_ALLOW_RESET'; Value = $savedReset },
        @{ Name = 'PULUJ_TEST_EVIDENCE_DIR'; Value = $savedEvidenceDirectory },
        @{ Name = 'PLAYWRIGHT_HTML_OUTPUT_DIR'; Value = $savedPlaywrightReportDirectory }
    )) {
        if ($null -eq $setting.Value) {
            Remove-Item "Env:$($setting.Name)" -ErrorAction SilentlyContinue
        } else {
            Set-Item "Env:$($setting.Name)" $setting.Value
        }
    }
}
