// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Puluj.Infrastructure.Persistence;

#nullable disable

namespace Puluj.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PulujDbContext))]
    [Migration("20260915085730_AddLlmRequestAudit")]
    partial class AddLlmRequestAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Puluj.Domain.Entities.AirAlert", b =>
                {
                    b.Property<long>("AirAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("air_alert_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AirAlertId"));

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasColumnName("alert_type");

                    b.Property<long?>("EndRawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("end_raw_message_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<string>("SourceAlertId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_alert_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<long?>("StartRawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("start_raw_message_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("AirAlertId")
                        .HasName("pk_air_alerts");

                    b.HasIndex("EndRawMessageId")
                        .HasDatabaseName("ix_air_alerts_end_raw_message_id");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_air_alerts_place_id")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("StartRawMessageId")
                        .HasDatabaseName("ix_air_alerts_start_raw_message_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_air_alerts_started_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StartedAt"), "brin");

                    b.HasIndex("SourceId", "SourceAlertId")
                        .IsUnique()
                        .HasDatabaseName("ix_air_alerts_source_id_source_alert_id");

                    b.ToTable("air_alerts", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.CollectorState", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<JsonDocument>("Cursor")
                        .HasColumnType("jsonb")
                        .HasColumnName("cursor");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<string>("LastSourceMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_source_message_id");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.HasKey("SourceId")
                        .HasName("pk_collector_states");

                    b.ToTable("collector_states", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.LlmRequest", b =>
                {
                    b.Property<long>("LlmRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("llm_request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LlmRequestId"));

                    b.Property<long?>("CacheCreationInputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_creation_input_tokens");

                    b.Property<long?>("CacheReadInputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_read_input_tokens");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("estimated_cost_usd");

                    b.Property<int>("FactsCount")
                        .HasColumnType("integer")
                        .HasColumnName("facts_count");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_version");

                    b.Property<long?>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<string>("RequestText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_text");

                    b.Property<string>("ResponseText")
                        .HasColumnType("text")
                        .HasColumnName("response_text");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<string>("Worker")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("worker");

                    b.HasKey("LlmRequestId")
                        .HasName("pk_llm_requests");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_llm_requests_occurred_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OccurredAt"), "brin");

                    b.HasIndex("RawMessageId")
                        .HasDatabaseName("ix_llm_requests_raw_message_id");

                    b.HasIndex("SourceId", "OccurredAt")
                        .HasDatabaseName("ix_llm_requests_source_id_occurred_at");

                    b.ToTable("llm_requests", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaceId"));

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("centroid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_key");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (geometry, 4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("KatottgCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("katottg_code");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("NameVariants")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("name_variants");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int?>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.Property<double>("RadiusKm")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_km");

                    b.HasKey("PlaceId")
                        .HasName("pk_places");

                    b.HasIndex("Centroid")
                        .HasDatabaseName("ix_places_centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "gist");

                    b.HasIndex("ExternalKey")
                        .IsUnique()
                        .HasDatabaseName("ix_places_external_key");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_places_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("KatottgCode")
                        .IsUnique()
                        .HasDatabaseName("ix_places_katottg_code")
                        .HasFilter("katottg_code IS NOT NULL");

                    b.HasIndex("NameVariants")
                        .HasDatabaseName("ix_places_name_variants");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameVariants"), "gin");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_places_parent_id");

                    b.HasIndex("Level", "CountryCode")
                        .HasDatabaseName("ix_places_level_country_code");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.ProcessingError", b =>
                {
                    b.Property<long>("ProcessingErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("processing_error_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProcessingErrorId"));

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long?>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.HasKey("ProcessingErrorId")
                        .HasName("pk_processing_errors");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_processing_errors_occurred_at");

                    b.HasIndex("RawMessageId")
                        .HasDatabaseName("ix_processing_errors_raw_message_id");

                    b.ToTable("processing_errors", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.RawMessage", b =>
                {
                    b.Property<long>("RawMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RawMessageId"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("claimed_by");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int?>("ProcessingMs")
                        .HasColumnType("integer")
                        .HasColumnName("processing_ms");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("processing_status");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<JsonDocument>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceMessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_message_id");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("RawMessageId")
                        .HasName("pk_raw_messages");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_raw_messages_hash");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_raw_messages_processing_status")
                        .HasFilter("processing_status = 0");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_raw_messages_published_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PublishedAt"), "brin");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_raw_messages_received_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ReceivedAt"), "brin");

                    b.HasIndex("SourceId", "SourceMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_raw_messages_source_id_source_message_id");

                    b.HasIndex(new[] { "ClaimedAt" }, "ix_raw_messages_in_progress_claimed_at")
                        .HasDatabaseName("ix_raw_messages_in_progress_claimed_at")
                        .HasFilter("processing_status = 4");

                    b.HasIndex(new[] { "PublishedAt" }, "ix_raw_messages_pending_published")
                        .HasDatabaseName("ix_raw_messages_pending_published")
                        .HasFilter("processing_status = 0");

                    b.ToTable("raw_messages", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SourceId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<JsonDocument>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<TimeSpan?>("PollingInterval")
                        .HasColumnType("interval")
                        .HasColumnName("polling_interval");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<JsonDocument>("Secrets")
                        .HasColumnType("jsonb")
                        .HasColumnName("secrets");

                    b.Property<double>("TrustLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("trust_level");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url");

                    b.HasKey("SourceId")
                        .HasName("pk_sources");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_code");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.SourceCopy", b =>
                {
                    b.Property<int>("CopierSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("copier_source_id");

                    b.Property<int>("OriginalSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("original_source_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<double>("DelaySecondsSum")
                        .HasColumnType("double precision")
                        .HasColumnName("delay_seconds_sum");

                    b.HasKey("CopierSourceId", "OriginalSourceId", "Day")
                        .HasName("pk_source_copies");

                    b.HasIndex("Day")
                        .HasDatabaseName("ix_source_copies_day");

                    b.ToTable("source_copies", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.SourceDailyStat", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("CopiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("copied_by");

                    b.Property<int>("Copies")
                        .HasColumnType("integer")
                        .HasColumnName("copies");

                    b.Property<double>("LeadSecondsSum")
                        .HasColumnType("double precision")
                        .HasColumnName("lead_seconds_sum");

                    b.Property<int>("Targets")
                        .HasColumnType("integer")
                        .HasColumnName("targets");

                    b.HasKey("SourceId", "Day")
                        .HasName("pk_source_daily_stats");

                    b.HasIndex("Day")
                        .HasDatabaseName("ix_source_daily_stats_day");

                    b.ToTable("source_daily_stats", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Target", b =>
                {
                    b.Property<long>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TargetId"));

                    b.Property<int>("AlertLevel")
                        .HasColumnType("integer")
                        .HasColumnName("alert_level");

                    b.Property<int>("ClassificationConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("classification_confidence");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<int?>("DestinationPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_place_id");

                    b.Property<int>("DirectionConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("direction_confidence");

                    b.Property<double?>("DirectionDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("direction_deg");

                    b.Property<int>("DirectionKind")
                        .HasColumnType("integer")
                        .HasColumnName("direction_kind");

                    b.Property<long?>("DuplicateOfTargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("duplicate_of_target_id");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<int>("IdentificationMethod")
                        .HasColumnType("integer")
                        .HasColumnName("identification_method");

                    b.Property<string>("IdentificationSource")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("identification_source");

                    b.Property<Geometry>("Location")
                        .HasColumnType("geography (geometry, 4326)")
                        .HasColumnName("location");

                    b.Property<double?>("LocationAccuracyKm")
                        .HasColumnType("double precision")
                        .HasColumnName("location_accuracy_km");

                    b.Property<int>("LocationKind")
                        .HasColumnType("integer")
                        .HasColumnName("location_kind");

                    b.Property<int?>("LocationPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("location_place_id");

                    b.Property<int>("ModelConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("model_confidence");

                    b.Property<int?>("ObjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("object_count");

                    b.Property<bool>("ObjectCountIsApproximate")
                        .HasColumnType("boolean")
                        .HasColumnName("object_count_is_approximate");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int?>("OriginPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_place_id");

                    b.Property<JsonDocument>("ParserMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("parser_metadata");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("parser_version");

                    b.Property<long>("RawMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_message_id");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("integer")
                        .HasColumnName("segment_index");

                    b.Property<string>("SegmentText")
                        .HasColumnType("text")
                        .HasColumnName("segment_text");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int?>("TargetCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("target_category_id");

                    b.Property<int?>("TargetClassId")
                        .HasColumnType("integer")
                        .HasColumnName("target_class_id");

                    b.Property<int?>("TargetFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("target_family_id");

                    b.Property<int?>("TargetModelId")
                        .HasColumnType("integer")
                        .HasColumnName("target_model_id");

                    b.HasKey("TargetId")
                        .HasName("pk_targets");

                    b.HasIndex("DestinationPlaceId")
                        .HasDatabaseName("ix_targets_destination_place_id");

                    b.HasIndex("DuplicateOfTargetId")
                        .HasDatabaseName("ix_targets_duplicate_of_target_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_targets_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("LocationPlaceId")
                        .HasDatabaseName("ix_targets_location_place_id");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("ix_targets_observed_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ObservedAt"), "brin");

                    b.HasIndex("OriginPlaceId")
                        .HasDatabaseName("ix_targets_origin_place_id");

                    b.HasIndex("RawMessageId")
                        .HasDatabaseName("ix_targets_raw_message_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_targets_source_id");

                    b.HasIndex("TargetFamilyId")
                        .HasDatabaseName("ix_targets_target_family_id");

                    b.HasIndex("TargetModelId")
                        .HasDatabaseName("ix_targets_target_model_id");

                    b.HasIndex("TargetCategoryId", "ObservedAt")
                        .HasDatabaseName("ix_targets_target_category_id_observed_at");

                    b.HasIndex("TargetClassId", "ObservedAt")
                        .HasDatabaseName("ix_targets_target_class_id_observed_at");

                    b.ToTable("targets", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetCategory", b =>
                {
                    b.Property<int>("TargetCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("target_category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TargetCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("TargetCategoryId")
                        .HasName("pk_target_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_target_categories_code");

                    b.ToTable("target_categories", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetClass", b =>
                {
                    b.Property<int>("TargetClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("target_class_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TargetClassId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("TargetCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("target_category_id");

                    b.HasKey("TargetClassId")
                        .HasName("pk_target_classes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_target_classes_code");

                    b.HasIndex("TargetCategoryId")
                        .HasDatabaseName("ix_target_classes_target_category_id");

                    b.ToTable("target_classes", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetFamily", b =>
                {
                    b.Property<int>("TargetFamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("target_family_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TargetFamilyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("TargetClassId")
                        .HasColumnType("integer")
                        .HasColumnName("target_class_id");

                    b.HasKey("TargetFamilyId")
                        .HasName("pk_target_families");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_target_families_code");

                    b.HasIndex("TargetClassId")
                        .HasDatabaseName("ix_target_families_target_class_id");

                    b.ToTable("target_families", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetLink", b =>
                {
                    b.Property<long>("FromTargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_target_id");

                    b.Property<long>("ToTargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_target_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_km");

                    b.Property<double?>("HeadingDiffDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("heading_diff_deg");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<double?>("MinutesApart")
                        .HasColumnType("double precision")
                        .HasColumnName("minutes_apart");

                    b.Property<double>("Probability")
                        .HasColumnType("double precision")
                        .HasColumnName("probability");

                    b.Property<double?>("RequiredMinutes")
                        .HasColumnType("double precision")
                        .HasColumnName("required_minutes");

                    b.HasKey("FromTargetId", "ToTargetId")
                        .HasName("pk_target_links");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_target_links_created_at");

                    b.HasIndex("ToTargetId")
                        .HasDatabaseName("ix_target_links_to_target_id");

                    b.ToTable("target_links", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetModel", b =>
                {
                    b.Property<int>("TargetModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("target_model_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TargetModelId"));

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("canonical_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("country");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("manufacturer");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("TargetFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("target_family_id");

                    b.HasKey("TargetModelId")
                        .HasName("pk_target_models");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_target_models_code");

                    b.HasIndex("TargetFamilyId")
                        .HasDatabaseName("ix_target_models_target_family_id");

                    b.ToTable("target_models", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetModelAlias", b =>
                {
                    b.Property<int>("TargetModelAliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("target_model_alias_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TargetModelAliasId"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alias");

                    b.Property<bool>("ExactMatch")
                        .HasColumnType("boolean")
                        .HasColumnName("exact_match");

                    b.Property<int>("ImpliedConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("implied_confidence");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("integer")
                        .HasColumnName("target_level");

                    b.HasKey("TargetModelAliasId")
                        .HasName("pk_target_model_aliases");

                    b.HasIndex("Alias", "Language", "TargetLevel", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("ix_target_model_aliases_alias_language_target_level_target_id");

                    b.ToTable("target_model_aliases", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetTrack", b =>
                {
                    b.Property<long>("TargetTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("target_track_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TargetTrackId"));

                    b.Property<string>("ClosedReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("closed_reason");

                    b.Property<int>("DirectionConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("direction_confidence");

                    b.Property<double?>("DirectionDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("direction_deg");

                    b.Property<int>("DirectionKind")
                        .HasColumnType("integer")
                        .HasColumnName("direction_kind");

                    b.Property<int>("DistinctSourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("distinct_source_count");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<Geometry>("LastLocation")
                        .HasColumnType("geography (geometry, 4326)")
                        .HasColumnName("last_location");

                    b.Property<double?>("LastLocationAccuracyKm")
                        .HasColumnType("double precision")
                        .HasColumnName("last_location_accuracy_km");

                    b.Property<int>("LastLocationKind")
                        .HasColumnType("integer")
                        .HasColumnName("last_location_kind");

                    b.Property<int?>("LastLocationPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("last_location_place_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int?>("LastSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("last_source_id");

                    b.Property<long?>("LastTargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_target_id");

                    b.Property<int>("ModelConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("model_confidence");

                    b.Property<int?>("ObjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("object_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TargetCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("target_category_id");

                    b.Property<int?>("TargetClassId")
                        .HasColumnType("integer")
                        .HasColumnName("target_class_id");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_count");

                    b.Property<int?>("TargetFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("target_family_id");

                    b.Property<int?>("TargetModelId")
                        .HasColumnType("integer")
                        .HasColumnName("target_model_id");

                    b.Property<int>("TrackConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("track_confidence");

                    b.Property<LineString>("TrackGeometry")
                        .HasColumnType("geometry (linestring, 4326)")
                        .HasColumnName("track_geometry");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TargetTrackId")
                        .HasName("pk_target_tracks");

                    b.HasIndex("LastLocation")
                        .HasDatabaseName("ix_target_tracks_last_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LastLocation"), "gist");

                    b.HasIndex("LastLocationPlaceId")
                        .HasDatabaseName("ix_target_tracks_last_location_place_id");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_target_tracks_last_seen_at");

                    b.HasIndex("TargetCategoryId")
                        .HasDatabaseName("ix_target_tracks_target_category_id");

                    b.HasIndex("TargetFamilyId")
                        .HasDatabaseName("ix_target_tracks_target_family_id");

                    b.HasIndex("TargetModelId")
                        .HasDatabaseName("ix_target_tracks_target_model_id");

                    b.HasIndex("Status", "LastSeenAt")
                        .HasDatabaseName("ix_target_tracks_status_last_seen_at");

                    b.HasIndex("TargetClassId", "Status")
                        .HasDatabaseName("ix_target_tracks_target_class_id_status");

                    b.ToTable("target_tracks", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetTrackRevision", b =>
                {
                    b.Property<long>("TargetTrackRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("target_track_revision_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TargetTrackRevisionId"));

                    b.Property<int>("DirectionConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("direction_confidence");

                    b.Property<double?>("DirectionDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("direction_deg");

                    b.Property<int>("DirectionKind")
                        .HasColumnType("integer")
                        .HasColumnName("direction_kind");

                    b.Property<Geometry>("LastLocation")
                        .HasColumnType("geography (geometry, 4326)")
                        .HasColumnName("last_location");

                    b.Property<double?>("LastLocationAccuracyKm")
                        .HasColumnType("double precision")
                        .HasColumnName("last_location_accuracy_km");

                    b.Property<int>("LastLocationKind")
                        .HasColumnType("integer")
                        .HasColumnName("last_location_kind");

                    b.Property<int?>("LastLocationPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("last_location_place_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("ModelConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("model_confidence");

                    b.Property<int?>("ObjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("object_count");

                    b.Property<DateTimeOffset>("RevisionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revision_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TargetCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("target_category_id");

                    b.Property<int?>("TargetClassId")
                        .HasColumnType("integer")
                        .HasColumnName("target_class_id");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer")
                        .HasColumnName("target_count");

                    b.Property<int?>("TargetFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("target_family_id");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<int?>("TargetModelId")
                        .HasColumnType("integer")
                        .HasColumnName("target_model_id");

                    b.Property<long>("TargetTrackId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_track_id");

                    b.Property<int>("TrackConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("track_confidence");

                    b.Property<LineString>("TrackGeometry")
                        .HasColumnType("geometry (linestring, 4326)")
                        .HasColumnName("track_geometry");

                    b.HasKey("TargetTrackRevisionId")
                        .HasName("pk_target_track_revisions");

                    b.HasIndex("RevisionAt")
                        .HasDatabaseName("ix_target_track_revisions_revision_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RevisionAt"), "brin");

                    b.HasIndex("TargetTrackId", "RevisionAt")
                        .HasDatabaseName("ix_target_track_revisions_target_track_id_revision_at");

                    b.ToTable("target_track_revisions", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TrackTarget", b =>
                {
                    b.Property<long>("TargetTrackId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_track_id");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<double>("AssociationConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("association_confidence");

                    b.Property<JsonDocument>("AssociationReason")
                        .HasColumnType("jsonb")
                        .HasColumnName("association_reason");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("TargetTrackId", "TargetId")
                        .HasName("pk_track_targets");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_track_targets_target_id");

                    b.ToTable("track_targets", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.UserLocation", b =>
                {
                    b.Property<Guid>("UserLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_location_id");

                    b.Property<string>("ClientKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_key");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserLocationId")
                        .HasName("pk_user_locations");

                    b.HasIndex("ClientKey")
                        .IsUnique()
                        .HasDatabaseName("ix_user_locations_client_key");

                    b.ToTable("user_locations", (string)null);
                });

            modelBuilder.Entity("Puluj.Domain.Entities.AirAlert", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_air_alerts_places_place_id");

                    b.HasOne("Puluj.Domain.Entities.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_air_alerts_sources_source_id");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.CollectorState", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Source", "Source")
                        .WithOne("CollectorState")
                        .HasForeignKey("Puluj.Domain.Entities.CollectorState", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collector_states_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.LlmRequest", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.RawMessage", "RawMessage")
                        .WithMany()
                        .HasForeignKey("RawMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_llm_requests_raw_messages_raw_message_id");

                    b.HasOne("Puluj.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_llm_requests_sources_source_id");

                    b.Navigation("RawMessage");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Place", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Place", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_places_places_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.RawMessage", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_raw_messages_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Target", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("DestinationPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_targets_places_destination_place_id");

                    b.HasOne("Puluj.Domain.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfTargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_targets_targets_duplicate_of_target_id");

                    b.HasOne("Puluj.Domain.Entities.Place", "LocationPlace")
                        .WithMany()
                        .HasForeignKey("LocationPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_targets_places_location_place_id");

                    b.HasOne("Puluj.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("OriginPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_targets_places_origin_place_id");

                    b.HasOne("Puluj.Domain.Entities.RawMessage", "RawMessage")
                        .WithMany("Targets")
                        .HasForeignKey("RawMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_targets_raw_messages_raw_message_id");

                    b.HasOne("Puluj.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_targets_sources_source_id");

                    b.HasOne("Puluj.Domain.Entities.TargetCategory", null)
                        .WithMany()
                        .HasForeignKey("TargetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_targets_target_categories_target_category_id");

                    b.HasOne("Puluj.Domain.Entities.TargetClass", null)
                        .WithMany()
                        .HasForeignKey("TargetClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_targets_target_classes_target_class_id");

                    b.HasOne("Puluj.Domain.Entities.TargetFamily", null)
                        .WithMany()
                        .HasForeignKey("TargetFamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_targets_target_families_target_family_id");

                    b.HasOne("Puluj.Domain.Entities.TargetModel", null)
                        .WithMany()
                        .HasForeignKey("TargetModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_targets_target_models_target_model_id");

                    b.Navigation("LocationPlace");

                    b.Navigation("RawMessage");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetClass", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.TargetCategory", "Category")
                        .WithMany("Classes")
                        .HasForeignKey("TargetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_classes_target_categories_target_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetFamily", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.TargetClass", "Class")
                        .WithMany("Families")
                        .HasForeignKey("TargetClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_families_target_classes_target_class_id");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetLink", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Target", "From")
                        .WithMany()
                        .HasForeignKey("FromTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_links_targets_from_target_id");

                    b.HasOne("Puluj.Domain.Entities.Target", "To")
                        .WithMany()
                        .HasForeignKey("ToTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_links_targets_to_target_id");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetModel", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.TargetFamily", "Family")
                        .WithMany("Models")
                        .HasForeignKey("TargetFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_models_target_families_target_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetTrack", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("LastLocationPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_target_tracks_places_last_location_place_id");

                    b.HasOne("Puluj.Domain.Entities.TargetCategory", null)
                        .WithMany()
                        .HasForeignKey("TargetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_target_tracks_target_categories_target_category_id");

                    b.HasOne("Puluj.Domain.Entities.TargetClass", null)
                        .WithMany()
                        .HasForeignKey("TargetClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_target_tracks_target_classes_target_class_id");

                    b.HasOne("Puluj.Domain.Entities.TargetFamily", null)
                        .WithMany()
                        .HasForeignKey("TargetFamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_target_tracks_target_families_target_family_id");

                    b.HasOne("Puluj.Domain.Entities.TargetModel", null)
                        .WithMany()
                        .HasForeignKey("TargetModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_target_tracks_target_models_target_model_id");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetTrackRevision", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.TargetTrack", "Track")
                        .WithMany()
                        .HasForeignKey("TargetTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_track_revisions_target_tracks_target_track_id");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TrackTarget", b =>
                {
                    b.HasOne("Puluj.Domain.Entities.Target", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_track_targets_targets_target_id");

                    b.HasOne("Puluj.Domain.Entities.TargetTrack", "Track")
                        .WithMany("Targets")
                        .HasForeignKey("TargetTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_targets_target_tracks_target_track_id");

                    b.Navigation("Target");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.RawMessage", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.Source", b =>
                {
                    b.Navigation("CollectorState");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetCategory", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetClass", b =>
                {
                    b.Navigation("Families");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetFamily", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Puluj.Domain.Entities.TargetTrack", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
